[format.rules]
  indent-style                    = "space"
  indent-sub-tables               = true
  indent-table-key-value-pairs    = true
  indent-width                    = 2
  key-value-equals-sign-alignment = true
  line-width                      = 88
